### ISSUE TITLE
Check if `astgrepr` works with `transform`

### ISSUE THREAD

**Issue by etiennebacher** [etiennebacher/astgrepr#17]
https://ast-grep.github.io/reference/yaml.html#patching

**Comment by etiennebacher** [comment]
Should be fairly simple, the most annoying part is actually having a good example of R code where this would be useful

**Comment by trevorld** [comment]
Unsure if this is an issue with `{astgrepr}` or `{flir}` but I seem to observe that if you have a `transform` statement that 

1. `lint_text()` throws an error:

```r
lint_text("expect_true(is.factor(x))")
Error in forderv(x, by = by, sort = FALSE, retGrp = TRUE) : 
  Column 8 passed to [f]order is type 'list', not yet supported.
```

2. `fix_text()` throws an error:

```r
fix_text("expect_true(is.factor(x))")
Error: Couldn't get value for meta-variable `CLASS`.
Are you sure it exists in the rule `expect_s3_class-3`?
```

Simplified rule of a rule I was trying to get to work.  To match {lintr}'s `expect_s3_class()` you need to grab the `S3CLASS` class name from more than a dozen `is.S3CLASS()` function names or else make more than a dozen extra patterns and I thought a simple ast-grep transform would be a straightforward way to do so following the ast-grep documentation:

https://ast-grep.github.io/guide/rewrite/transform.html#rewrite-with-regex-capture-groups

```yml

id: expect_s3_class-3
language: r
severity: warning
rule:
  pattern: expect_true($ISF($X))
constraints:
  ISF:
    any:
      - regex: "^is\\.data\\.frame$"
      - regex: "^is\\.factor$"
transform:
  CLASS:
    replace:
      source: $ISF
      replace: "is\\.(?<ISFCLASS>.*)"
      by: "$ISFCLASS"
fix: expect_s3_class(~~X~~, ~~CLASS~~)
message: expect_s3_class(x, k) is better than expect_true(is.<k>(x))
```
