### ISSUE TITLE
`node_replace()` removes escaped characters 

### ISSUE THREAD

**Issue by etiennebacher** [etiennebacher/astgrepr#24]
`foo.yml`:

```yaml
id: foobar
language: r
severity: warning
rule:
  pattern: $A = $B
fix: ~~A~~ <- ~~B~~
message: foo
```
```r
src <- 'lab = gsub("\\s+", "", lab)'

root <- src |>
  tree_new() |>
  tree_root()

res <- root |>
  node_find(files = "foo.yml") 

res |> 
  node_replace(
    foobar = "~~A~~ <- ~~B~~"
  )
```
```
[[1]]
[[1]][[1]]
[1] 0

[[1]][[2]]
[1] 26

[[1]][[3]]
[1] "lab <- gsub(\"s+\", \"\", lab)"


attr(,"class")
[1] "astgrep_replacement" "list"  
```
