### ISSUE TITLE
Replacement shouldn't change formatting

### ISSUE THREAD

**Issue by etiennebacher** [etiennebacher/astgrepr#27]
``` r
flint::fix_text("
expect_equal(
  names(x),
  c('a', 'b')
)
")
#> Old code:
#> expect_equal(
#>   names(x),
#>   c('a', 'b')
#> )
#> 
#> New code:
#> expect_named(x, c('a', 'b'))
```

**Comment by etiennebacher** [comment]
```r
src <- "
expect_equal(
  names(x),
  c('a', 'b')
)
"

root <- src |>
  tree_new() |>
  tree_root()

nodes_to_replace <- root |>
  node_find(files = "foo.yml")

fixes <- nodes_to_replace |>
  node_replace(
    `expect_named-2` = "expect_named(~~OBJ~~, ~~VALUES~~)"
  )

tree_rewrite(root, fixes)
```
```yaml
id: expect_named-2
language: r
severity: warning
rule:
  pattern:
    context: expect_equal(names($OBJ), $VALUES)
    strictness: ast
fix: expect_named(~~OBJ~~, ~~VALUES~~)
message: expect_named(x, n) is better than expect_equal(names(x), n).
```
